### ISSUE TITLE
100% CPU usage in recv

### ISSUE THREAD

**Issue by copy** [rgrinberg/async-zmq#2]
When using `recv`, CPU usage jumps to 100% until a message arrives. A reproducible testcase is the `rep` sample.

**Comment by copy** [comment]
The `rep` binary in `lwt-zmq` doesn't have this problem.

The issue comes from [`wrap`](https://github.com/rgrinberg/async-zmq/blob/master/lib/async_zmq.ml#L36) repeatedly entering `idle_loop`. `lwt-zmq` doesn't have this problem because `Lwt_unix.wrap_syscall` does some magic sleep before it is resolved.

**Comment by rgrinberg** [comment]
I missed this issue, thanks for reminding me. You're right, `Lwt_unix.wrap_syscall` indeed performs the magic of registering the fd with lwt's event loop to wake up the lwt thread once there is something to read.

I don't know how to replicate that with Async but will take a look.

Also, Lwt's re-implementation no top of async might provide useful clues on how to accomplish this as well if you're interested in tackling this:

https://github.com/janestreet/lwt-async/blob/master/src/unix/lwt_unix.ml#L323-L372

**Comment by copy** [comment]
Interesting. I'll give it a shot.
