### ISSUE TITLE
Port to jbuilder

### ISSUE THREAD

**Issue by copy** [rgrinberg/async-zmq#7]

**Comment by rgrinberg** [comment]
I think this package should really be folded into the main zmq package. Unfortunately the zmq maintainer isn't being very responsive.

**Comment by copy** [comment]
Closing as this project has been merged into https://github.com/issuu/ocaml-zmq (including fixing this issue).

@rgrinberg I'd suggest to archive this project on github, link to https://github.com/issuu/ocaml-zmq and notify users of the async-zmq opam package.
